# Generated by Django 3.2 on 2021-04-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='Feature',
            new_name='feature',
        ),
    ]
