# Generated by Django 3.2 on 2021-05-06 00:44

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_feature_feature_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('precocusto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de custo')),
                ('precovenda', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço de venda')),
                ('promocao', models.BooleanField(default=False, verbose_name='Promoção?')),
                ('imagem', stdimage.models.StdImageField(upload_to='produto', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
