# Generated by Django 3.2 on 2021-05-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
