# Generated by Django 3.2 on 2021-05-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='precopromo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Preço de promoção'),
            preserve_default=False,
        ),
    ]
